# Form implementation generated from reading ui file 'rimtointeger.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 240)
        MainWindow.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 671, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(153, 255, 241);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineinput = QtWidgets.QLineEdit(self.centralwidget)
        self.lineinput.setGeometry(QtCore.QRect(60, 120, 230, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lineinput.setFont(font)
        self.lineinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineinput.setObjectName("lineinput")
        self.labeloutput = QtWidgets.QLabel(self.centralwidget)
        self.labeloutput.setGeometry(QtCore.QRect(400, 120, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.labeloutput.setFont(font)
        self.labeloutput.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.labeloutput.setText("")
        self.labeloutput.setObjectName("labeloutput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Convert rim number to decimal"))
